/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto */

#ifndef _Included_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
#define _Included_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_OPENSSL_SUCCESS
#define com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_OPENSSL_SUCCESS 1L
#undef com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_OPENSSL_FAILURE
#define com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_OPENSSL_FAILURE 0L
/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3CreateCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3CreateCtx
  (JNIEnv *, jobject);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3FreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3FreeCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3Update
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3Update
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3Final
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3Final
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3Reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3Reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3Clone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3Clone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3OneShotDigest
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3OneShotDigest
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3hmacCreateCtx
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3hmacCreateCtx
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3hmacFreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3hmacFreeCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3hmacUpdate
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3hmacUpdate
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3hmacFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3hmacFinal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3hmacReset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3hmacReset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3hmacClone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3hmacClone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm3hmacOneShotMac
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm3hmacOneShotMac
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm4CreateCtx
 * Signature: (ZLjava/lang/String;Z[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm4CreateCtx
  (JNIEnv *, jobject, jboolean, jstring, jboolean, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm4FreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm4FreeCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm4Update
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm4Update
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm4Final
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm4Final
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm4GCMSetIV
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm4GCMSetIV
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm4GCMUpdateAAD
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm4GCMUpdateAAD
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm4GCMProcTag
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm4GCMProcTag
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2ToUncompPubKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2ToUncompPubKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2GenPubKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2GenPubKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2ValidatePoint
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2ValidatePoint
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2KeyPairGenCreateCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2KeyPairGenCreateCtx
  (JNIEnv *, jobject);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2KeyPairGenFreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2KeyPairGenFreeCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2KeyPairGenGenKeyPair
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2KeyPairGenGenKeyPair
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2OneShotKeyPairGenGenKeyPair
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2OneShotKeyPairGenGenKeyPair
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2CipherCreateCtx
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2CipherCreateCtx
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2CipherFreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2CipherFreeCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2CipherEncrypt
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2CipherEncrypt
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2CipherDecrypt
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2CipherDecrypt
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2OneShotCipherEncrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2OneShotCipherEncrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2OneShotCipherDecrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2OneShotCipherDecrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2SignatureCreateCtx
 * Signature: ([B[BZ)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2SignatureCreateCtx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2SignatureFreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2SignatureFreeCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2SignatureSign
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2SignatureSign
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2SignatureVerify
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2SignatureVerify
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2OneShotSignatureSign
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2OneShotSignatureSign
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2OneShotSignatureVerify
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2OneShotSignatureVerify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2KeyExCreateCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2KeyExCreateCtx
  (JNIEnv *, jobject);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2KeyExFreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2KeyExFreeCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2DeriveKey
 * Signature: (J[B[B[B[B[B[B[BZI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2DeriveKey
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jboolean, jint);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    sm2OneShotDeriveKey
 * Signature: ([B[B[B[B[B[B[BZI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_sm2OneShotDeriveKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jboolean, jint);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecOneShotKeyPairGenGenKeyPair
 * Signature: (I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecOneShotKeyPairGenGenKeyPair
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecKeyPairGenCreateCtx
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecKeyPairGenCreateCtx
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecKeyPairGenFreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecKeyPairGenFreeCtx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecKeyPairGenGenKeyPair
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecKeyPairGenGenKeyPair
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecdsaCreateCtx
 * Signature: (II[BZ)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecdsaCreateCtx
  (JNIEnv *, jclass, jint, jint, jbyteArray, jboolean);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecdsaFreeCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecdsaFreeCtx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecdsaSign
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecdsaSign
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecdsaVerify
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecdsaVerify
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecdsaOneShotSign
 * Signature: (II[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecdsaOneShotSign
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto
 * Method:    ecdsaOneShotVerify
 * Signature: (II[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_kona_crypto_provider_nativeImpl_NativeCrypto_ecdsaOneShotVerify
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
