#
# Copyright (C) 2023, THL A29 Limited, a Tencent company. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#

name: Build on PR

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source
        uses: actions/checkout@v4

      - name: Run precheck script
        run: bash ./.github/workflows/scripts/precheck.sh
        shell: bash

  gradle:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [precheck]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11, 17, 21]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Execute Gradle build
        run: ./gradlew clean build
