name: Execute build on PR

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source
        uses: actions/checkout@v4

      - name: Run precheck script
        run: bash ./.github/workflows/scripts/precheck.sh
        shell: bash

  gradle:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [precheck]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11, 17]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the source
        uses: actions/checkout@v4

      - name: Set up JDKs
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Execute Gradle build
        run: ./gradlew clean build
